import { PrismaClient } from "@prisma/client";
import bcrypt from "bcryptjs";
import crypto from "crypto";

const prisma = new PrismaClient();

function makeHash(data: object) {
  return crypto.createHash("sha256").update(JSON.stringify(data)).digest("hex");
}

const scholarships = [
  {
    namaBeasiswa: "Beasiswa LPDP Program Doktor",
    penyelenggara: "Lembaga Pengelola Dana Pendidikan (LPDP)",
    lokasi: "DALAM_NEGERI",
    pilihanLokasi: JSON.stringify(["Jakarta", "Bandung", "Yogyakarta", "Surabaya", "Makassar"]),
    skemaPembiayaan: "Fully Funded",
    jenisPembiayaan: "Beasiswa Penuh",
    komponenPembiayaan: JSON.stringify(["SPP/Tuition Fee", "Tunjangan Hidup Bulanan", "Tunjangan Buku", "Tunjangan Penelitian", "Tunjangan Seminar Internasional"]),
    keterangan: "LPDP memberikan beasiswa doktor untuk perguruan tinggi terbaik dalam negeri. Program ini mencakup semua biaya pendidikan dan biaya hidup selama masa studi. Pendaftar harus memiliki LoA dari perguruan tinggi tujuan atau mendaftar melalui jalur reguler LPDP.",
    linkPendaftaran: "https://beasiswalpdp.kemenkeu.go.id",
    sumberCrawling: "manual",
    deadline: new Date("2025-03-31"),
    status: "PUBLISHED",
    isManualEntry: true,
  },
  {
    namaBeasiswa: "LPDP Program Doktor Luar Negeri",
    penyelenggara: "Lembaga Pengelola Dana Pendidikan (LPDP)",
    lokasi: "LUAR_NEGERI",
    pilihanLokasi: JSON.stringify(["Amerika Serikat", "Inggris", "Australia", "Jerman", "Belanda", "Jepang", "Korea Selatan"]),
    skemaPembiayaan: "Fully Funded",
    jenisPembiayaan: "Beasiswa Penuh",
    komponenPembiayaan: JSON.stringify(["Tuition Fee", "Living Allowance", "Tiket Pesawat PP", "Tunjangan Kedatangan", "Asuransi Kesehatan", "Dana Penelitian"]),
    keterangan: "Program beasiswa LPDP untuk studi doktor di perguruan tinggi terkemuka di luar negeri. Wajib kembali ke Indonesia setelah menyelesaikan studi dan berkontribusi pada pembangunan bangsa.",
    linkPendaftaran: "https://beasiswalpdp.kemenkeu.go.id",
    sumberCrawling: "manual",
    deadline: new Date("2025-03-31"),
    status: "PUBLISHED",
    isManualEntry: true,
  },
  {
    namaBeasiswa: "DAAD Research Grants – Doctoral Programmes in Germany",
    penyelenggara: "Deutscher Akademischer Austauschdienst (DAAD)",
    lokasi: "LUAR_NEGERI",
    pilihanLokasi: JSON.stringify(["Jerman"]),
    skemaPembiayaan: "Fully Funded",
    jenisPembiayaan: "Beasiswa Penelitian",
    komponenPembiayaan: JSON.stringify(["Monthly Stipend", "Travel Allowance", "Health Insurance", "Research Grant"]),
    keterangan: "DAAD menawarkan beasiswa penelitian doktoral di universitas-universitas Jerman. Program ini cocok bagi peneliti yang ingin berkolaborasi dengan institusi Jerman. Tersedia dalam berbagai bidang keilmuan termasuk ilmu sosial, teknik, sains, dan humaniora.",
    linkPendaftaran: "https://www.daad.de/en/study-and-research-in-germany/scholarships/",
    sumberCrawling: "manual",
    deadline: new Date("2025-10-15"),
    status: "PUBLISHED",
    isManualEntry: true,
  },
  {
    namaBeasiswa: "Chevening Scholarships",
    penyelenggara: "UK Government / Foreign, Commonwealth & Development Office",
    lokasi: "LUAR_NEGERI",
    pilihanLokasi: JSON.stringify(["Inggris"]),
    skemaPembiayaan: "Fully Funded",
    jenisPembiayaan: "Beasiswa Penuh",
    komponenPembiayaan: JSON.stringify(["Tuition Fees", "Living Expenses", "Return Flights", "Arrival Allowance", "Thesis/Dissertation Grant", "Study Travel Grant"]),
    keterangan: "Chevening adalah program beasiswa internasional pemerintah Inggris yang memberikan kesempatan bagi individu berbakat dari seluruh dunia untuk belajar di universitas-universitas terbaik Inggris. Program doktor tersedia di semua bidang studi.",
    linkPendaftaran: "https://www.chevening.org/scholarships/",
    sumberCrawling: "manual",
    deadline: new Date("2025-11-05"),
    status: "PUBLISHED",
    isManualEntry: true,
  },
  {
    namaBeasiswa: "Australia Awards Scholarships",
    penyelenggara: "Australian Government – Department of Foreign Affairs and Trade",
    lokasi: "LUAR_NEGERI",
    pilihanLokasi: JSON.stringify(["Australia"]),
    skemaPembiayaan: "Fully Funded",
    jenisPembiayaan: "Beasiswa Penuh",
    komponenPembiayaan: JSON.stringify(["Tuition Fees", "Return Air Travel", "Establishment Allowance", "Contribution to Living Expenses", "Overseas Student Health Cover", "Academic Support"]),
    keterangan: "Australia Awards adalah beasiswa bergengsi yang diberikan pemerintah Australia kepada warga negara berkembang termasuk Indonesia. Program ini mendukung studi doktor di universitas-universitas Australia terbaik. Penerima beasiswa diharapkan kembali ke negara asal untuk berkontribusi pada pembangunan.",
    linkPendaftaran: "https://www.australiaawardsindonesia.org",
    sumberCrawling: "manual",
    deadline: new Date("2025-04-30"),
    status: "PUBLISHED",
    isManualEntry: true,
  },
  {
    namaBeasiswa: "Fulbright Presidential Scholarship",
    penyelenggara: "American Indonesian Exchange Foundation (AMINEF) / US Government",
    lokasi: "LUAR_NEGERI",
    pilihanLokasi: JSON.stringify(["Amerika Serikat"]),
    skemaPembiayaan: "Fully Funded",
    jenisPembiayaan: "Beasiswa Penuh",
    komponenPembiayaan: JSON.stringify(["Tuition and Fees", "Monthly Maintenance Allowance", "Round-trip Air Travel", "Health Insurance", "Book and Research Allowance"]),
    keterangan: "Program Fulbright Presidential Scholarship menawarkan kesempatan bagi warga negara Indonesia untuk melanjutkan studi S3 di Amerika Serikat. Program ini merupakan hasil kerja sama antara pemerintah Indonesia dan Amerika Serikat melalui AMINEF.",
    linkPendaftaran: "https://www.aminef.or.id/grants-for-indonesians/fulbright-programs/",
    sumberCrawling: "manual",
    deadline: new Date("2025-02-15"),
    status: "PUBLISHED",
    isManualEntry: true,
  },
  {
    namaBeasiswa: "Beasiswa Pendidikan Indonesia (BPI) Program Doktor",
    penyelenggara: "Kementerian Pendidikan, Kebudayaan, Riset, dan Teknologi",
    lokasi: "DALAM_NEGERI",
    pilihanLokasi: JSON.stringify(["Seluruh Indonesia"]),
    skemaPembiayaan: "Fully Funded",
    jenisPembiayaan: "Beasiswa Penuh",
    komponenPembiayaan: JSON.stringify(["Biaya Pendidikan", "Biaya Hidup", "Biaya Buku", "Biaya Penelitian Disertasi"]),
    keterangan: "BPI adalah program beasiswa dari Kemendikbudristek untuk mendukung peningkatan kualifikasi tenaga pendidik di Indonesia, termasuk dosen perguruan tinggi. Program ini memprioritaskan dosen yang belum bergelar doktor.",
    linkPendaftaran: "https://beasiswa.kemdikbud.go.id",
    sumberCrawling: "manual",
    deadline: new Date("2025-05-30"),
    status: "PUBLISHED",
    isManualEntry: true,
  },
  // ── Tambahan crawler baru ──────────────────────────────────
  {
    namaBeasiswa: "Beasiswa 5000 Doktor Kemenag — Dalam Negeri",
    penyelenggara: "Kementerian Agama Republik Indonesia",
    lokasi: "DALAM_NEGERI",
    pilihanLokasi: JSON.stringify(["Seluruh Indonesia"]),
    skemaPembiayaan: "Fully Funded",
    jenisPembiayaan: "Beasiswa Penuh",
    komponenPembiayaan: JSON.stringify(["Biaya Pendidikan (SPP)", "Biaya Hidup Bulanan", "Biaya Penelitian/Disertasi", "Biaya Buku"]),
    keterangan: "Program Beasiswa 5000 Doktor Kemenag jalur dalam negeri ditujukan bagi dosen/calon dosen PTKI (Perguruan Tinggi Keagamaan Islam) negeri maupun swasta di bawah naungan Kemenag. Program ini bertujuan meningkatkan kualifikasi akademik dosen PTKI yang belum bergelar doktor. Tersedia untuk semua bidang ilmu yang relevan dengan pengembangan PTKI.",
    linkPendaftaran: "https://beasiswa.kemenag.go.id",
    sumberCrawling: "manual",
    deadline: new Date("2025-06-30"),
    status: "PUBLISHED",
    isManualEntry: true,
  },
  {
    namaBeasiswa: "Beasiswa 5000 Doktor Kemenag — Luar Negeri",
    penyelenggara: "Kementerian Agama Republik Indonesia",
    lokasi: "LUAR_NEGERI",
    pilihanLokasi: JSON.stringify(["Mesir", "Arab Saudi", "Maroko", "Yordania", "Malaysia", "Amerika Serikat", "Jerman", "Australia"]),
    skemaPembiayaan: "Fully Funded",
    jenisPembiayaan: "Beasiswa Penuh",
    komponenPembiayaan: JSON.stringify(["Biaya Pendidikan (SPP)", "Biaya Hidup Bulanan", "Biaya Penelitian/Disertasi", "Tiket Pesawat PP", "Asuransi Kesehatan", "Biaya Visa"]),
    keterangan: "Program Beasiswa 5000 Doktor Kemenag jalur luar negeri memungkinkan dosen PTKI untuk melanjutkan studi doktor di universitas-universitas terkemuka di berbagai negara. Prioritas diberikan pada bidang studi keislaman, hukum Islam, pendidikan Islam, ekonomi Islam, dan bidang terkait lainnya. Peserta wajib kembali ke PTKI asal setelah menyelesaikan studi.",
    linkPendaftaran: "https://beasiswa.kemenag.go.id",
    sumberCrawling: "manual",
    deadline: new Date("2025-06-30"),
    status: "PUBLISHED",
    isManualEntry: true,
  },
  {
    namaBeasiswa: "MEXT Research Student Scholarship (Embassy Recommendation)",
    penyelenggara: "Ministry of Education, Culture, Sports, Science and Technology (MEXT) Japan",
    lokasi: "LUAR_NEGERI",
    pilihanLokasi: JSON.stringify(["Jepang"]),
    skemaPembiayaan: "Fully Funded",
    jenisPembiayaan: "Beasiswa Penuh",
    komponenPembiayaan: JSON.stringify(["Biaya Kuliah Penuh", "Tunjangan Hidup Bulanan (¥143.000–¥145.000)", "Tiket Pesawat PP", "Bebas Biaya Ujian Masuk & Pendaftaran"]),
    keterangan: "Beasiswa MEXT (Monbukagakusho) jalur Kedutaan adalah program beasiswa pemerintah Jepang yang sangat bergengsi. Tersedia untuk program Research Student yang dapat dilanjutkan ke program doktor. Pendaftar mengajukan melalui Kedutaan Besar Jepang di Jakarta. Tersedia untuk semua bidang studi. Durasi: 3,5 tahun (6 bulan research student + 3 tahun doktor). Pendaftaran biasanya dibuka Mei–Juni setiap tahun.",
    linkPendaftaran: "https://www.id.emb-japan.go.jp/sch.html",
    sumberCrawling: "manual",
    deadline: new Date("2025-06-30"),
    status: "PUBLISHED",
    isManualEntry: true,
  },
  {
    namaBeasiswa: "Türkiye Bursları — Doctorate Scholarship",
    penyelenggara: "Pemerintah Republik Turki (Türkiye Bursları / YTB)",
    lokasi: "LUAR_NEGERI",
    pilihanLokasi: JSON.stringify(["Turki"]),
    skemaPembiayaan: "Fully Funded",
    jenisPembiayaan: "Beasiswa Penuh",
    komponenPembiayaan: JSON.stringify(["Biaya Kuliah Penuh", "Tunjangan Hidup Bulanan", "Akomodasi Asrama", "Asuransi Kesehatan", "Tiket Pesawat PP", "Kursus Bahasa Turki (1 tahun)"]),
    keterangan: "Türkiye Bursları adalah program beasiswa resmi pemerintah Turki yang dikelola oleh YTB. Sangat populer di kalangan alumni pesantren dan NU. Program doktor tersedia di ratusan universitas Turki termasuk universitas-universitas Islam ternama. Pendaftaran sepenuhnya online. Deadline biasanya Februari setiap tahun.",
    linkPendaftaran: "https://www.turkiyeburslari.gov.tr",
    sumberCrawling: "manual",
    deadline: new Date("2026-02-20"),
    status: "PUBLISHED",
    isManualEntry: true,
  },
  {
    namaBeasiswa: "Chinese Government Scholarship (CSC) — Embassy Recommendation",
    penyelenggara: "China Scholarship Council (CSC) / Pemerintah Tiongkok",
    lokasi: "LUAR_NEGERI",
    pilihanLokasi: JSON.stringify(["China"]),
    skemaPembiayaan: "Fully Funded",
    jenisPembiayaan: "Beasiswa Penuh",
    komponenPembiayaan: JSON.stringify(["Biaya Kuliah Penuh", "Akomodasi Asrama", "Tunjangan Hidup Bulanan (CNY 3.500)", "Asuransi Kesehatan Komprehensif", "Tiket Pesawat PP"]),
    keterangan: "Beasiswa Pemerintah China jalur Kedutaan Besar China di Jakarta. Program doktor tersedia di lebih dari 270 universitas di China. Tersedia program berbahasa Inggris. Beberapa universitas memiliki program Islamic Studies. Pendaftaran biasanya Maret–April setiap tahun melalui website KBRI China.",
    linkPendaftaran: "https://www.campuschina.org",
    sumberCrawling: "manual",
    deadline: new Date("2026-04-15"),
    status: "PUBLISHED",
    isManualEntry: true,
  },
  {
    namaBeasiswa: "IsDB Merit Scholarship for High Technology",
    penyelenggara: "Islamic Development Bank (IsDB)",
    lokasi: "LUAR_NEGERI",
    pilihanLokasi: JSON.stringify(["Negara Anggota OKI", "Arab Saudi", "Malaysia", "Turki", "Mesir"]),
    skemaPembiayaan: "Fully Funded",
    jenisPembiayaan: "Beasiswa Penuh",
    komponenPembiayaan: JSON.stringify(["Biaya Kuliah Penuh", "Tunjangan Hidup Bulanan", "Tiket Pesawat PP", "Asuransi Kesehatan", "Dana Penelitian", "Tunjangan Kedatangan"]),
    keterangan: "Program beasiswa IsDB untuk warga negara anggota OKI termasuk Indonesia. Fokus pada bidang sains, teknologi, teknik, matematika (STEM), serta ilmu sosial dan keagamaan Islam. Program doktor tersedia di universitas-universitas terkemuka di negara anggota OKI. Dosen dan akademisi dari perguruan tinggi Islam diprioritaskan.",
    linkPendaftaran: "https://www.isdb.org/what-we-do/develop-human-capital/scholarship",
    sumberCrawling: "manual",
    deadline: null,
    status: "PUBLISHED",
    isManualEntry: true,
  },
  {
    namaBeasiswa: "BRIN Beasiswa Program Doktor — Co-promotion",
    penyelenggara: "Badan Riset dan Inovasi Nasional (BRIN)",
    lokasi: "LUAR_NEGERI",
    pilihanLokasi: JSON.stringify(["Belanda", "Australia", "Jerman", "Jepang", "Amerika Serikat"]),
    skemaPembiayaan: "Fully Funded",
    jenisPembiayaan: "Beasiswa Riset Co-promotion",
    komponenPembiayaan: JSON.stringify(["Biaya Pendidikan", "Tunjangan Hidup", "Tiket Pesawat PP", "Asuransi Kesehatan", "Dana Penelitian"]),
    keterangan: "Program co-promotion BRIN memungkinkan doktor diarahkan oleh dua promotor: satu dari Indonesia dan satu dari universitas mitra luar negeri. Mahasiswa menghabiskan waktu riset di kedua negara. Cocok untuk dosen yang ingin membangun jaringan riset internasional. Tersedia juga skema dalam negeri di pusat riset BRIN.",
    linkPendaftaran: "https://brin.go.id/beasiswa",
    sumberCrawling: "manual",
    deadline: null,
    status: "PUBLISHED",
    isManualEntry: true,
  },
  {
    namaBeasiswa: "Erasmus Mundus Joint Doctorate (EMJD)",
    penyelenggara: "European Commission — Erasmus+ Programme",
    lokasi: "LUAR_NEGERI",
    pilihanLokasi: JSON.stringify(["Eropa (multi-negara)", "Prancis", "Jerman", "Belanda", "Italia", "Spanyol", "Belgia"]),
    skemaPembiayaan: "Fully Funded",
    jenisPembiayaan: "Beasiswa Doktor Bersama (Joint Doctorate)",
    komponenPembiayaan: JSON.stringify(["Living Allowance (€1.500/bulan)", "Travel & Installation Grant", "Research & Training Costs", "Tuition Fees", "Asuransi Kesehatan"]),
    keterangan: "Erasmus Mundus Joint Doctorate adalah program beasiswa penuh dari Komisi Eropa. Mahasiswa belajar di minimal 2 universitas Eropa dan mendapatkan gelar doktor bersama (joint/double degree). Tersedia ratusan program di semua bidang ilmu: humaniora, ilmu sosial, sains, teknik. Deadline bervariasi per program, biasanya November–Januari.",
    linkPendaftaran: "https://www.eacea.ec.europa.eu/scholarships/erasmus-mundus-catalogue_en",
    sumberCrawling: "manual",
    deadline: null,
    status: "PUBLISHED",
    isManualEntry: true,
  },
  {
    namaBeasiswa: "Korean Government Scholarship Program (KGSP) – Graduate",
    penyelenggara: "National Institute for International Education (NIIED), Korea",
    lokasi: "LUAR_NEGERI",
    pilihanLokasi: JSON.stringify(["Korea Selatan"]),
    skemaPembiayaan: "Fully Funded",
    jenisPembiayaan: "Beasiswa Penuh",
    komponenPembiayaan: JSON.stringify(["Tuition Fees", "Monthly Stipend", "Airfare", "Medical Insurance", "Korean Language Training", "Settlement Allowance"]),
    keterangan: "KGSP (GKS) menawarkan beasiswa penuh untuk program S3 di universitas Korea Selatan terpilih. Termasuk program persiapan bahasa Korea selama 1 tahun sebelum memulai program doktor.",
    linkPendaftaran: "https://www.studyinkorea.go.kr/en/sub/gks/allnew_invite.do",
    sumberCrawling: "manual",
    deadline: new Date("2025-09-28"),
    status: "PUBLISHED",
    isManualEntry: true,
  },

  // ── Batch 3: Semua prodi UNU Yogyakarta ──────────────────
  {
    namaBeasiswa: "Stipendium Hungaricum — Doctoral Programme",
    penyelenggara: "Pemerintah Hongaria — Tempus Public Foundation",
    lokasi: "LUAR_NEGERI",
    pilihanLokasi: JSON.stringify(["Hongaria"]),
    skemaPembiayaan: "Fully Funded",
    jenisPembiayaan: "Beasiswa Penuh",
    komponenPembiayaan: JSON.stringify(["Biaya Kuliah Penuh", "Tunjangan Hidup Bulanan (HUF 140.000 ≈ Rp 5,5 juta)", "Akomodasi Asrama atau Tunjangan Sewa", "Asuransi Kesehatan"]),
    keterangan: "Stipendium Hungaricum tersedia untuk SEMUA bidang studi doktor: Manajemen, Akuntansi, Farmasi, Teknik Elektro, Informatika, Teknik Komputer, Pertanian, Agribisnis, Pendidikan (PGSD/PBI), dan Studi Islam. Tersedia di 30+ universitas Hongaria. Kompetisi relatif lebih terbuka dibanding beasiswa Eropa Barat. Pendaftaran melalui SHAP online. Deadline biasanya Januari setiap tahun.",
    linkPendaftaran: "https://stipendiumhungaricum.hu/apply/",
    sumberCrawling: "manual",
    deadline: new Date("2026-01-15"),
    status: "PUBLISHED",
    isManualEntry: true,
  },
  {
    namaBeasiswa: "SEARCA Graduate Scholarship — Doctoral (Luar Negeri)",
    penyelenggara: "SEARCA (Southeast Asian Regional Center for Graduate Study and Research in Agriculture)",
    lokasi: "LUAR_NEGERI",
    pilihanLokasi: JSON.stringify(["Filipina", "Thailand", "Malaysia", "Vietnam"]),
    skemaPembiayaan: "Fully Funded",
    jenisPembiayaan: "Beasiswa Riset Pertanian",
    komponenPembiayaan: JSON.stringify(["Biaya Kuliah Penuh", "Tunjangan Hidup Bulanan", "Tiket Pesawat PP", "Asuransi Kesehatan", "Dana Penelitian/Disertasi", "Biaya Konferensi"]),
    keterangan: "SEARCA menyediakan beasiswa doktor untuk warga negara Asia Tenggara di bidang pertanian, teknologi pangan, agribisnis, kehutanan, dan lingkungan hidup. Sangat relevan untuk prodi Teknologi Hasil Pertanian dan Agribisnis UNU Yogyakarta. Pendaftaran dibuka dua kali setahun. Ada juga skema In-Country (studi di universitas dalam Indonesia).",
    linkPendaftaran: "https://www.searca.org/scholarships",
    sumberCrawling: "manual",
    deadline: null,
    status: "PUBLISHED",
    isManualEntry: true,
  },
  {
    namaBeasiswa: "SEARCA In-Country Scholarship — Doctoral (Dalam Negeri)",
    penyelenggara: "SEARCA (Southeast Asian Regional Center for Graduate Study and Research in Agriculture)",
    lokasi: "DALAM_NEGERI",
    pilihanLokasi: JSON.stringify(["Yogyakarta", "Bogor", "Malang", "Makassar"]),
    skemaPembiayaan: "Fully Funded",
    jenisPembiayaan: "Beasiswa Riset Pertanian",
    komponenPembiayaan: JSON.stringify(["Biaya Kuliah Penuh", "Tunjangan Hidup Bulanan", "Dana Penelitian/Disertasi", "Biaya Publikasi Jurnal"]),
    keterangan: "Skema SEARCA In-Country memungkinkan studi doktor di universitas Indonesia (UGM, IPB, UNHAS, UNAND). Cocok untuk dosen yang tidak ingin meninggalkan keluarga jangka panjang. Bidang: pertanian, pangan, agribisnis, lingkungan hidup.",
    linkPendaftaran: "https://www.searca.org/scholarships",
    sumberCrawling: "manual",
    deadline: null,
    status: "PUBLISHED",
    isManualEntry: true,
  },
  {
    namaBeasiswa: "ADB–Japan Scholarship Program (JSP) — Doctoral",
    penyelenggara: "Asian Development Bank (ADB) & Pemerintah Jepang",
    lokasi: "LUAR_NEGERI",
    pilihanLokasi: JSON.stringify(["Jepang", "Filipina", "Thailand", "India", "Singapura", "Pakistan", "Sri Lanka"]),
    skemaPembiayaan: "Fully Funded",
    jenisPembiayaan: "Beasiswa Penuh",
    komponenPembiayaan: JSON.stringify(["Biaya Kuliah Penuh", "Tunjangan Hidup Bulanan", "Tiket Pesawat PP", "Asuransi Kesehatan", "Dana Buku & Penelitian", "Tunjangan Disertasi", "Biaya Visa"]),
    keterangan: "ADB-JSP adalah beasiswa bergengsi didanai pemerintah Jepang, dikelola Asian Development Bank. Program doktor untuk: ekonomi pembangunan, manajemen, kebijakan publik, agribisnis, lingkungan hidup, ilmu sosial. Peserta wajib kembali ke negara asal. Tersedia di 10 universitas mitra ADB terbaik di Asia. Relevan untuk prodi Manajemen, Akuntansi, Agribisnis UNU Yogyakarta.",
    linkPendaftaran: "https://www.adb.org/site/careers/japan-scholarship-program",
    sumberCrawling: "manual",
    deadline: null,
    status: "PUBLISHED",
    isManualEntry: true,
  },
  {
    namaBeasiswa: "Al-Azhar University Scholarship — Program Doktor (S3)",
    penyelenggara: "Universitas Al-Azhar — Mesir",
    lokasi: "LUAR_NEGERI",
    pilihanLokasi: JSON.stringify(["Mesir (Kairo)"]),
    skemaPembiayaan: "Fully Funded",
    jenisPembiayaan: "Beasiswa Penuh",
    komponenPembiayaan: JSON.stringify(["Biaya Kuliah Penuh", "Tunjangan Hidup Bulanan", "Akomodasi Mahasiswa", "Tiket Pesawat PP", "Akses Perpustakaan & Riset"]),
    keterangan: "Al-Azhar adalah universitas Islam tertua dan paling bergengsi di dunia di Kairo. Program doktor: Ushuluddin, Syariah, Bahasa Arab, Dirasat Islamiyah, Tarbiyah Islam, dan Ekonomi Islam. Koneksi historis NU–Al-Azhar sangat kuat. Pendaftaran melalui Kemenag RI atau langsung ke Al-Azhar. Bahasa pengantar: Arab.",
    linkPendaftaran: "https://www.azhar.edu.eg/en/international-students",
    sumberCrawling: "manual",
    deadline: null,
    status: "PUBLISHED",
    isManualEntry: true,
  },
  {
    namaBeasiswa: "Saudi Cultural Mission (SACM) — Doctoral Scholarship",
    penyelenggara: "Saudi Cultural Mission (SACM) / Pemerintah Arab Saudi",
    lokasi: "LUAR_NEGERI",
    pilihanLokasi: JSON.stringify(["Arab Saudi (Riyadh, Jeddah, Madinah, Makkah)"]),
    skemaPembiayaan: "Fully Funded",
    jenisPembiayaan: "Beasiswa Penuh",
    komponenPembiayaan: JSON.stringify(["Biaya Kuliah Penuh", "Tunjangan Hidup Bulanan (SAR 1.900)", "Akomodasi/Tunjangan Perumahan", "Tiket Pesawat PP", "Asuransi Kesehatan", "Tunjangan Buku"]),
    keterangan: "SACM menyediakan beasiswa doktor di universitas Arab Saudi terkemuka: Universitas Islam Madinah, King Abdulaziz, King Faisal, King Saud. Bidang: Studi Islam, Syariah, Bahasa Arab, Ekonomi Islam, Pendidikan Islam. Sangat relevan untuk prodi Studi Islam Interdisipliner UNU Yogyakarta.",
    linkPendaftaran: "https://www.sacm.org.sa",
    sumberCrawling: "manual",
    deadline: null,
    status: "PUBLISHED",
    isManualEntry: true,
  },
  {
    namaBeasiswa: "Moroccan Government Scholarship — Doctoral (Maroko)",
    penyelenggara: "Pemerintah Kerajaan Maroko / AMCI",
    lokasi: "LUAR_NEGERI",
    pilihanLokasi: JSON.stringify(["Maroko (Rabat, Casablanca, Fes)"]),
    skemaPembiayaan: "Fully Funded",
    jenisPembiayaan: "Beasiswa Penuh",
    komponenPembiayaan: JSON.stringify(["Biaya Kuliah Penuh", "Tunjangan Hidup Bulanan", "Akomodasi", "Asuransi Kesehatan"]),
    keterangan: "Maroko menawarkan beasiswa doktor melalui AMCI untuk studi di universitas Maroko. Bidang: Studi Islam, Bahasa Arab, Hukum Islam, Filsafat, Sosial. Pendaftaran melalui Kedutaan Maroko di Jakarta. Bahasa pengantar: Arab dan Prancis.",
    linkPendaftaran: "https://www.amci.ma",
    sumberCrawling: "manual",
    deadline: null,
    status: "PUBLISHED",
    isManualEntry: true,
  },
  {
    namaBeasiswa: "Eiffel Excellence Scholarship — Doctoral Level (Prancis)",
    penyelenggara: "Campus France / Kementerian Luar Negeri Prancis",
    lokasi: "LUAR_NEGERI",
    pilihanLokasi: JSON.stringify(["Prancis (Paris, Lyon, Toulouse, Bordeaux, Strasbourg)"]),
    skemaPembiayaan: "Fully Funded",
    jenisPembiayaan: "Beasiswa Penuh",
    komponenPembiayaan: JSON.stringify(["Tunjangan Hidup Bulanan (€1.400/bulan)", "Tiket Pesawat PP", "Asuransi Kesehatan Komprehensif", "Dana Kebudayaan & Sosial", "Biaya Transportasi dalam Kota"]),
    keterangan: "Eiffel Excellence Scholarship dari Kementerian Luar Negeri Prancis tersedia untuk: teknik & ilmu alam, ekonomi & manajemen, ilmu politik & hukum, dan humaniora. Pendaftaran dilakukan melalui institusi Prancis yang menominasikan kandidat (bukan mendaftar langsung). Deadline biasanya Januari. Relevan untuk Manajemen, Akuntansi, Informatika, Teknik Elektro UNU Yogyakarta.",
    linkPendaftaran: "https://www.campusfrance.org/en/eiffel-scholarship-program-of-excellence",
    sumberCrawling: "manual",
    deadline: new Date("2026-01-10"),
    status: "PUBLISHED",
    isManualEntry: true,
  },
  {
    namaBeasiswa: "Singapore International Graduate Award (SINGA)",
    penyelenggara: "A*STAR, NUS, NTU & SUTD — Singapura",
    lokasi: "LUAR_NEGERI",
    pilihanLokasi: JSON.stringify(["Singapura"]),
    skemaPembiayaan: "Fully Funded",
    jenisPembiayaan: "Beasiswa Riset Penuh",
    komponenPembiayaan: JSON.stringify(["Biaya Kuliah Penuh (4 tahun)", "Tunjangan Hidup Bulanan (SGD 2.000 ≈ Rp 23 juta)", "Tunjangan Perjalanan Awal (SGD 1.000)", "Asuransi Kesehatan", "Dana Konferensi"]),
    keterangan: "SINGA adalah beasiswa doktor di Singapura oleh A*STAR, NUS, NTU, dan SUTD. Bidang: biomedis, informatika & AI, teknik elektro, material, kimia, fisika, ilmu pangan & bioteknologi. Sangat relevan untuk prodi Informatika, Teknik Komputer, Teknik Elektro, dan Farmasi UNU Yogyakarta. Singapura dekat, bahasa Inggris. Deadline Juni & Desember.",
    linkPendaftaran: "https://www.a-star.edu.sg/Scholarships/for-graduate-studies/singapore-international-graduate-award-singa",
    sumberCrawling: "manual",
    deadline: null,
    status: "PUBLISHED",
    isManualEntry: true,
  },
  {
    namaBeasiswa: "WUR PhD Fellowship Programme — Wageningen University",
    penyelenggara: "Wageningen University & Research (WUR) — Belanda",
    lokasi: "LUAR_NEGERI",
    pilihanLokasi: JSON.stringify(["Belanda (Wageningen)"]),
    skemaPembiayaan: "Fully Funded",
    jenisPembiayaan: "Beasiswa Riset Penuh",
    komponenPembiayaan: JSON.stringify(["Biaya Kuliah & Riset Penuh (4 tahun)", "Tunjangan Hidup Bulanan (≈€1.700)", "Tiket Pesawat PP", "Asuransi Kesehatan", "Dana Konferensi Internasional", "Fasilitas Lab Kelas Dunia"]),
    keterangan: "Wageningen University & Research (WUR) adalah universitas peringkat #1 dunia untuk ilmu pertanian, pangan, dan lingkungan hidup. Program PhD: ilmu pangan & teknologi, agronomi, hortikultura, agribisnis, bioteknologi, gizi, kehutanan. Sangat relevan untuk prodi Teknologi Hasil Pertanian dan Agribisnis UNU Yogyakarta. Posisi PhD diiklankan di website WUR.",
    linkPendaftaran: "https://www.wur.nl/en/education-programmes/phd-programmes.htm",
    sumberCrawling: "manual",
    deadline: null,
    status: "PUBLISHED",
    isManualEntry: true,
  },
  {
    namaBeasiswa: "NFP — Netherlands Fellowship Programme (Belanda)",
    penyelenggara: "Nuffic / Pemerintah Belanda",
    lokasi: "LUAR_NEGERI",
    pilihanLokasi: JSON.stringify(["Belanda (Amsterdam, Utrecht, Wageningen, Delft, Groningen)"]),
    skemaPembiayaan: "Fully Funded",
    jenisPembiayaan: "Beasiswa Penuh",
    komponenPembiayaan: JSON.stringify(["Biaya Kuliah Penuh", "Tunjangan Hidup Bulanan", "Tiket Pesawat PP", "Asuransi Kesehatan & Kecelakaan", "Visa & Izin Tinggal", "Tunjangan Kedatangan"]),
    keterangan: "NFP oleh Nuffic mendukung studi doktor di universitas Belanda: WUR, TU Delft, Universitas Amsterdam, Utrecht, Groningen. Terbuka untuk semua bidang: pertanian, teknik, sosial, manajemen. Prioritas untuk peserta dari negara berkembang yang bekerja di sektor pembangunan.",
    linkPendaftaran: "https://www.nuffic.nl/en/subjects/scholarships/netherlands-fellowship-programme-nfp",
    sumberCrawling: "manual",
    deadline: null,
    status: "PUBLISHED",
    isManualEntry: true,
  },
  {
    namaBeasiswa: "Google PhD Fellowship Program",
    penyelenggara: "Google LLC",
    lokasi: "LUAR_NEGERI",
    pilihanLokasi: JSON.stringify(["Amerika Serikat", "Eropa", "Asia Pasifik"]),
    skemaPembiayaan: "Partial",
    jenisPembiayaan: "Industry Fellowship",
    komponenPembiayaan: JSON.stringify(["Stipend (USD 10.000/tahun)", "Dana Riset (USD 5.000/tahun)", "Biaya Konferensi", "Mentoring dari Peneliti Google"]),
    keterangan: "Google PhD Fellowship mendukung mahasiswa doktor di: AI & Machine Learning, Algoritma, HCI, Komputasi Kuantum, Keamanan Siber, NLP, Data Mining. Kandidat dinominasikan oleh universitas. Sangat relevan untuk prodi Informatika, Teknik Komputer, dan Teknik Elektro UNU Yogyakarta.",
    linkPendaftaran: "https://research.google/programs-and-events/phd-fellowship/",
    sumberCrawling: "manual",
    deadline: null,
    status: "PUBLISHED",
    isManualEntry: true,
  },
  {
    namaBeasiswa: "Ford Foundation International Fellowships Program",
    penyelenggara: "Ford Foundation",
    lokasi: "LUAR_NEGERI",
    pilihanLokasi: JSON.stringify(["Amerika Serikat", "Eropa", "Asia", "Afrika"]),
    skemaPembiayaan: "Fully Funded",
    jenisPembiayaan: "Foundation Fellowship",
    komponenPembiayaan: JSON.stringify(["Biaya Kuliah Penuh", "Tunjangan Hidup Bulanan", "Tiket Pesawat PP", "Asuransi Kesehatan", "Dana Buku & Penelitian", "Dana Darurat"]),
    keterangan: "Ford Foundation Fellowship untuk pemimpin masa depan dari komunitas kurang terwakili. Fokus: pendidikan, ilmu sosial, humaniora, kebijakan publik, studi Islam, pembangunan komunitas. Sangat relevan untuk prodi PGSD, PBI, Studi Islam, Manajemen, dan Akuntansi UNU Yogyakarta.",
    linkPendaftaran: "https://www.fordfoundation.org/work/our-grants/fellows-program/",
    sumberCrawling: "manual",
    deadline: null,
    status: "PUBLISHED",
    isManualEntry: true,
  },
  {
    namaBeasiswa: "British Council — GREAT Scholarships untuk Indonesia",
    penyelenggara: "British Council Indonesia",
    lokasi: "LUAR_NEGERI",
    pilihanLokasi: JSON.stringify(["Inggris"]),
    skemaPembiayaan: "Fully Funded",
    jenisPembiayaan: "Beasiswa Penuh",
    komponenPembiayaan: JSON.stringify(["Biaya Kuliah Penuh", "Tunjangan Hidup", "Tiket Pesawat PP", "Asuransi Kesehatan"]),
    keterangan: "British Council mengelola GREAT Scholarships dan program kemitraan kampus UK untuk Indonesia. Sangat relevan untuk prodi PBI (Pendidikan Bahasa Inggris) dan PGSD. Sering ada program khusus bidang pendidikan dan pengajaran bahasa. Hubungi British Council Jakarta untuk program terkini.",
    linkPendaftaran: "https://www.britishcouncil.or.id/en/study-uk/scholarships",
    sumberCrawling: "manual",
    deadline: null,
    status: "PUBLISHED",
    isManualEntry: true,
  },
  {
    namaBeasiswa: "SEAMEO Scholarships — Pendidikan Asia Tenggara",
    penyelenggara: "Southeast Asian Ministers of Education Organization (SEAMEO)",
    lokasi: "LUAR_NEGERI",
    pilihanLokasi: JSON.stringify(["Thailand", "Malaysia", "Singapura", "Filipina", "Vietnam"]),
    skemaPembiayaan: "Fully Funded",
    jenisPembiayaan: "Beasiswa Riset Pendidikan",
    komponenPembiayaan: JSON.stringify(["Biaya Kuliah Penuh", "Tunjangan Hidup", "Tiket Pesawat PP", "Dana Penelitian"]),
    keterangan: "SEAMEO menyediakan beasiswa dan fellowship untuk pendidik dan peneliti pendidikan Asia Tenggara. Pusat riset SEAMEO (QITEP in Language, QITEP in Math, RECSAM) sangat relevan untuk prodi PGSD dan PBI. Indonesia memiliki pusat SEAMEO aktif di Yogyakarta dan Jakarta.",
    linkPendaftaran: "https://www.seameo.org",
    sumberCrawling: "manual",
    deadline: null,
    status: "PUBLISHED",
    isManualEntry: true,
  },
  {
    namaBeasiswa: "Microsoft Research PhD Fellowship",
    penyelenggara: "Microsoft Research",
    lokasi: "LUAR_NEGERI",
    pilihanLokasi: JSON.stringify(["Amerika Serikat", "Eropa", "Asia"]),
    skemaPembiayaan: "Partial",
    jenisPembiayaan: "Industry Fellowship",
    komponenPembiayaan: JSON.stringify(["Stipend Tahunan", "Dana Riset", "Biaya Konferensi & Travel", "Internship di Microsoft Research", "Mentoring Peneliti Senior"]),
    keterangan: "Microsoft Research PhD Fellowship mendukung mahasiswa doktor di computing research. Bidang: AI, ML, Systems, Theory, HCI, Programming Languages, Security, Applied Sciences. Mencakup bantuan finansial dan kesempatan magang di lab Microsoft Research. Relevan untuk prodi Informatika dan Teknik Komputer UNU Yogyakarta.",
    linkPendaftaran: "https://www.microsoft.com/en-us/research/academic-program/phd-fellowship/",
    sumberCrawling: "manual",
    deadline: null,
    status: "PUBLISHED",
    isManualEntry: true,
  },
];

async function main() {
  console.log("Seeding database...");

  // Create admin user
  const hashedPassword = await bcrypt.hash(
    process.env.ADMIN_DEFAULT_PASSWORD || "admin123",
    12
  );

  await prisma.adminUser.upsert({
    where: { email: "admin@unu.ac.id" },
    update: {},
    create: {
      email: "admin@unu.ac.id",
      password: hashedPassword,
      name: "Administrator UNU",
    },
  });
  console.log("Admin user created: admin@unu.ac.id");

  // Seed scholarships
  for (const s of scholarships) {
    const hashData = {
      namaBeasiswa: s.namaBeasiswa,
      penyelenggara: s.penyelenggara,
      linkPendaftaran: s.linkPendaftaran,
      deadline: s.deadline?.toISOString(),
    };
    const contentHash = makeHash(hashData);

    await prisma.scholarship.upsert({
      where: {
        id: crypto
          .createHash("md5")
          .update(s.namaBeasiswa + s.penyelenggara)
          .digest("hex")
          .slice(0, 24),
      },
      update: {},
      create: {
        id: crypto
          .createHash("md5")
          .update(s.namaBeasiswa + s.penyelenggara)
          .digest("hex")
          .slice(0, 24),
        ...s,
        contentHash,
        reviewedBy: "system-seed",
        reviewedAt: new Date(),
      },
    });
  }

  console.log(`Seeded ${scholarships.length} scholarships.`);
  console.log("Done.");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
